### PR TITLE
Add support for proxying an API endpoint.

### PR DESCRIPTION
**Pull request by WadeBarnes**

### CODE REVIEW

**Comment by sheaphillips** [comment]
observation - the template will end up having the proxying for API_URL regardless of whether API_URL is defined...this could cause problems for apps that have an /api route that they serve up themselves and *don't want* forwarded. is there a way to only insert that snippet if API_URL is defined?

**Comment by WadeBarnes** [comment]
Conditional statements (i.e. if) are considered Evil.  So the best thing may be to rewrite the whole /api location section into the config only if API_URL is defined.  Thoughts?

**Comment by sheaphillips** [comment]
My thought was not to put a coniditional in that NGINX would see, but something that is evaluated when the conf file is generated - e.g. in the logic within the `run` script, detect if API_URL is defined, and append /insert the appropriate block into the conf file if it is.

**Comment by WadeBarnes** [comment]
Exactly what I am proposing/recommending.

**Comment by WadeBarnes** [comment]
So replace the section
```
# proxy requests to API
location /api/ {
proxy_pass %API_URL%;
}
```
with
```		
%API_PROXY_CONFIG%
```

Which would be replaced with either a blank string or a configuration section complete with URL.

**Comment by sheaphillips** [comment]
+1
ᐧ

**Comment by WadeBarnes** [comment]
@sheaphillips, I've updated the code based on our discussion.

**Pull request merged**
